### ISSUE TITLE
Fmask on occasion fails

### ISSUE THREAD

**Issue by geoderek** [SouthFACT/landsatfact-data#35] opened 2015-06-16 20:09 UTC
Running Fmask
tiffFolder: /fsdata1/lsfdata/tarFiles/extractedTars/LE70310382015125EDC00
working dir:/fsdata1/lsfdata/tarFiles

Fmask Fail:
/usr/local/MATLAB/MATLAB_Compiler_Runtime/v80/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v80/bin/glnxa64:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v80/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v80/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v80/sys/java/jre/glnxa64/jre/lib/amd64/server:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v80/sys/java/jre/glnxa64/jre/lib/amd64
/usr/local/MATLAB/MATLAB_Compiler_Runtime/v80/X11/app-defaults
Warning: No display specified.  You will not be able to display graphics on the screen.
Fmask 3.0 beta version start ...
Dilate 3 cloud pixels 3 shadow pixels for 22.50 cloud probability
Read in header information and TIF images
From DNs to TOA ref & BT
Read in TOA ref ...
Cloud and cloud shadow matching ...
Out of memory. Type HELP MEMORY for your options.
Error in fcssm (line 285)
Error in Fmask (line 8)
Error in autoFmask (line 73)
MATLAB:nomem
255
Script Terminated

**Comment by geoderek** [comment] 2015-06-17 17:13
Installed onto our cloud server [subprocess32](https://pypi.python.org/pypi/subprocess32/) which we hope to to be an improvement over the subprocess
[subprocess](https://docs.python.org/2/library/subprocess.html).  Adjusted the FMASK call within the geoprocessing script to use this hopefully improved version of subprocess when calling FMASK.  Re-ran a test on the last days scenes (4 scenes) and the geoprocessing script runs through to completion...???     After some testing the behavior is somewhat still inconsistent in its performance, meaning I can't still get it to memory error out.  So at this point I can say for sure this has fixed the issue.  I think we still need to look up upgrading FMASK and correspondingly MCR.

**Comment by geoderek** [comment] 2015-06-30 01:50
Installing/Upgrading to 3.2 version Linux package of Fmask on Cloud4:
Note: some of the pre-requisites where likely installed by the previously described steps (e.g. installing libxmu).  This is opposed to the older beta version of Fmask I running (3.0 beta version).  Anyhow, it also requires an upgrade to the MCR to 8.1 of that particular software.
mkdir Fmask32
cd Fmask32
wget http://ftp-earth.bu.edu/public/zhuzhe/Fmask_Linux_3.2v/Fmask_pkg.zip
unzip Fmask_pkg.zip
unzip MCRInstaller.zip -d MCR
sudo ./install -mode silent -agreeToLicense yes

LD_LIBRARY_PATH: /usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/bin/glnxa64:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/java/jre/glnxa64/jre/lib/amd64/server:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/java/jre/glnxa64/jre/lib/amd64

To test this new installation of Fmask I found a problematic TAR file (LC80240352015180LGN00) then CD to directory where extracted Landsat TAR file is and run the shell script accordingly:

> sh /var/vsites/landsatfact-data-dev.nemac.org/project/geoprocessing/fmaskLinux/Fmask32/runFmask32.sh
> /usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/bin/glnxa64:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/java/jre/glnxa64/jre/lib/amd64/server:/usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/sys/java/jre/glnxa64/jre/lib/amd64
> /usr/local/MATLAB/MATLAB_Compiler_Runtime/v81/X11/app-defaults
> Warning: No display specified.  You will not be able to display graphics on the screen.
> Fmask 3.2.1 beta version start ...
> Cloud, cloud shadow, and snow detection for Landsat 8 images
> Cloud/cloud shadow/snow dilated by 3/3/0 pixels (default)
> Cloud probability threshold of 22.50% (default)
> Read in header information & TIF images
> From DNs to TOA ref & BT
> Out of memory. Type HELP MEMORY for your options.
> Error in nd2toarbt (line 617)
> Error in plcloud (line 35)
> Error in Fmask (line 7)
> Error in autoFmask (line 119)
> MATLAB:nomem

So the error is still there... I really think this is potentially something like a RAM issue on this size of server doing this level of processing. But, the good news is that we are operating now with the latest version of Fmask and Fmask often works... but not everytime consistently.

**Comment by mwhutchi** [comment] 2015-10-14 21:03
We haven't had this type of error since using the new server. So I am closing this issue.

**Closed as completed by mwhutchi** 2015-10-14 21:03 UTC

**Comment by Digdgeo** [comment] 2015-11-20 14:29
Hi, I am still having these issues: 

 The matlab windows says: 'Expected input number 1, i1, or BW1, to be non NaN.
Error in autoFmask.m at line 119'

This happens aorund a 5-10% of the scenes that I try to process. I am running 3.2.1 Fmask version with Landsat 8.

Thanks

**Comment by Opadera** [comment] 2016-02-11 07:42
I get a similar error when trying to run Fmask 3.2 on a Landsat 8 scene. How did you resolve the issue?

Additional error info:

```
Cloud, cloud shadow, and snow detection for Landsat 8 images
Cloud/cloud shadow/snow dilated by 3/3/0 pixels (default)
Cloud probability threshold of 22.50% (default)
Read in header information & TIF images
From DNs to TOA ref & BT
Error using imfill
Expected input number 1, I1 or BW1, to be non-NaN.

Error in imfill>parse_inputs (line 168)



Error in imfill (line 124)



Error in plcloud (line 203)



Error in Fmask (line 7)



Error in autoFmask (line 119)



MATLAB:imfill:expectedNonNaN
```

**Comment by Digdgeo** [comment] 2016-02-11 09:48
Hi unnic, 

I've just realize that some of the scenes that give me an error, have been reprocesed again for the USGS. So, if you go to glovis and download the scenes again, maybe you could see that the processed date ("FILE DATE" in the MTL) have changed. I don't understand what happens, because band values seems to be the same. But now, I can run Fmask in these new processed images without any issues.

**Comment by Opadera** [comment] 2016-02-12 12:28
Ok, thanks. I tried that but still get the error. basically I cant process any image from December 2015 until today (for older images it works).
Do you have an account on stackoverflow? I'd open a topic there because I want to avoid spamming this repository with my fmask error

**Comment by daveism** [comment] 2016-02-12 13:32
@unnic @Digdgeo  we switched to a version of FMASK ( https://github.com/prs021/fmask ) that does not use the thermal band.  The problem was due to issues with tirs and landsat 8.  You can see the alerts on the this website. http://landsat.usgs.gov/mission_headlines2016.php  Because of the tirs issue  all values in the tirs bands was 0.  FMASK 3.2 would fail with a divide by zero, although that was not the error message, that is what was happening.   It looks like the TIRs issue is now fixed  and the images are being reprocessed which is explains what you are seeing. Hope this helps.

**Comment by Digdgeo** [comment] 2016-02-13 16:44
Thanks so much Daveism, that was the problem. I can run now with the Sentinel 2 Fmask version the scenes not yet reprocessed!

**Comment by Opadera** [comment] 2016-02-15 08:19
Thanks for your input @daveism. Unfortunately I don't have matlab and have to wait for the standalone version of fmask 3.3, but good to know that the issue is taken care of.

EDIT: ok, using the fmask standalone version 3.2 from github (Landsat 8 images without TIRS (Sentinel 2 scenario) ) seems to work for the scences in question. Thanks a lot!

**Comment by Digdgeo** [comment] 2016-07-22 14:43
Hey, someone knows how to run Fmask with Sentinel 2? I have both Fmask 3_2 and 3.3 and both are working with Landsat 8 but whenever I try to run a S2 I get a message saying that there's not a L*MTL.txt in the folder. So I don't know how to say to Fmask that my image is a S2.

Other thing, I have S2 original (downloaded from the scihub) with all the tiles, which folder should I point to run Fmask (Main folder with all the tiles, Granule tile folder, etc.). I also have S2 scenes downloaded and processed from the Semi Automatic Classification Plugin, can Fmask run on these scenes?

Thanks
