### ISSUE TITLE
Write results of geoprocessing scripts to products table 

### ISSUE THREAD

**Issue by mwhutchi** [SouthFACT/landsatfact-data#31] opened 2015-05-27 19:53 UTC
At the end of the geoprocessing scripts, the resulting .tif files that are created need to be written to the products table.

**Comment by geoderek** [comment] 2015-05-27 20:02
[This](https://github.com/nemac/landsatfact-data/blob/master/geoprocessing/landsatFACTmain.py) is the script that will likely need to be updated.

**Comment by geoderek** [comment] 2015-06-18 13:57
duplicate of https://github.com/nemac/landsatfact-data/issues/34

**Closed as completed by geoderek** 2015-06-18 13:57 UTC
